Update default jetty version to 8.1.5

diff --git a/templates/default/jetty.initd.erb b/templates/default/jetty.initd.erb
--- a/templates/default/jetty.initd.erb
+++ b/templates/default/jetty.initd.erb
@@ -1,30 +1,30 @@
-#!/usr/bin/env bash  
+#!/usr/bin/env bash
 #
 # Startup script for jetty under *nix systems (it works under NT/cygwin too).
 
 # To get the service to restart correctly on reboot, uncomment below (3 lines):
 # ========================
 # chkconfig: 3 99 99
-# description: Jetty 7 webserver
+# description: Jetty 8 webserver
 # processname: jetty
 # ========================
 
 # Configuration files
 #
 # /etc/default/jetty
-#   If it exists, this is read at the start of script. It may perform any 
+#   If it exists, this is read at the start of script. It may perform any
 #   sequence of shell commands, like setting relevant environment variables.
 #
 # $HOME/.jettyrc
-#   If it exists, this is read at the start of script. It may perform any 
+#   If it exists, this is read at the start of script. It may perform any
 #   sequence of shell commands, like setting relevant environment variables.
 #
 # /etc/jetty.conf
 #   If found, and no configurations were given on the command line,
-#   the file will be used as this script's configuration. 
+#   the file will be used as this script's configuration.
 #   Each line in the file may contain:
 #     - A comment denoted by the pound (#) sign as first non-blank character.
-#     - The path to a regular file, which will be passed to jetty as a 
+#     - The path to a regular file, which will be passed to jetty as a
 #       config.xml file.
 #     - The path to a directory. Each *.xml file in the directory will be
 #       passed to jetty as a config.xml file.
@@ -34,15 +34,11 @@
 # $JETTY_HOME/etc/jetty.xml
 #   If found, used as this script's configuration file, but only if
 #   /etc/jetty.conf was not present. See above.
-#   
+#
 # Configuration variables
 #
-# JAVA_HOME  
-#   Home of Java installation. 
-#
 # JAVA
-#   Command to invoke Java. If not set, $JAVA_HOME/bin/java will be
-#   used.
+#   Command to invoke Java. If not set, java (from the PATH) will be used.
 #
 # JAVA_OPTIONS
 #   Extra options to pass to the JVM
@@ -54,7 +50,7 @@
 #   and /opt/jetty. The java system property "jetty.home" will be
 #   set to this value for use by configure.xml files, f.e.:
 #
-#    <Arg><SystemProperty name="jetty.home" default="."/>/webapps/jetty.war</Arg>
+#    <Arg><Property name="jetty.home" default="."/>/webapps/jetty.war</Arg>
 #
 # JETTY_PORT
 #   Override the default port for Jetty servers. If not set then the
@@ -64,7 +60,7 @@
 #   used in the demo config files to respect this property in Listener
 #   configuration elements:
 #
-#    <Set name="Port"><SystemProperty name="jetty.port" default="8080"/></Set>
+#    <Set name="Port"><Property name="jetty.port" default="8080"/></Set>
 #
 #   Note: that the config file could ignore this property simply by saying:
 #
@@ -73,10 +69,10 @@
 # JETTY_RUN
 #   Where the jetty.pid file should be stored. It defaults to the
 #   first available of /var/run, /usr/var/run, and /tmp if not set.
-#  
+#
 # JETTY_PID
 #   The Jetty PID file, defaults to $JETTY_RUN/jetty.pid
-#   
+#
 # JETTY_ARGS
 #   The default arguments to pass to jetty.
 #
@@ -101,10 +97,10 @@ findDirectory()
   local L OP=$1
   shift
   for L in "$@"; do
-    [ "$OP" "$L" ] || continue 
+    [ "$OP" "$L" ] || continue
     printf %s "$L"
     break
-  done 
+  done
 }
 
 running()
@@ -118,9 +114,6 @@ readConfig()
   (( DEBUG )) && echo "Reading $1.."
   source "$1"
 }
-
-
-
 
 
 
@@ -143,8 +136,8 @@ shift
 ##################################################
 # Read any configuration files
 ##################################################
-for CONFIG in /etc/default/jetty{,7} $HOME/.jettyrc; do
-  if [ -f "$CONFIG" ] ; then 
+for CONFIG in /etc/default/jetty{,8} $HOME/.jettyrc; do
+  if [ -f "$CONFIG" ] ; then
     readConfig "$CONFIG"
   fi
 done
@@ -164,7 +157,7 @@ JETTY_INSTALL_TRACE_FILE="etc/jetty.xml"
 ##################################################
 # Try to determine JETTY_HOME if not set
 ##################################################
-if [ -z "$JETTY_HOME" ] 
+if [ -z "$JETTY_HOME" ]
 then
   JETTY_SH=$0
   case "$JETTY_SH" in
@@ -175,7 +168,7 @@ then
   JETTY_HOME=${JETTY_SH%/*/*}
 
   if [ ! -f "${JETTY_SH%/*/*}/$JETTY_INSTALL_TRACE_FILE" ]
-  then 
+  then
     JETTY_HOME=
   fi
 fi
@@ -199,28 +192,42 @@ if [ -z "$JETTY_HOME" ] ; then
         "/home"
         )
   JETTY_DIR_NAMES=(
-        "jetty-7"
-        "jetty7"
-        "jetty-7.*"
+        "jetty-8"
+        "jetty8"
+        "jetty-8.*"
         "jetty"
-        "Jetty-7"
-        "Jetty7"
-        "Jetty-7.*"
+        "Jetty-8"
+        "Jetty8"
+        "Jetty-8.*"
         "Jetty"
         )
-        
+
   for L in "${STANDARD_LOCATIONS[@]}"
   do
     for N in "${JETTY_DIR_NAMES[@]}"
     do
-      JETTY_HOME=("$L/"$N)
-      if [ ! -d "$JETTY_HOME" ] || [ ! -f "$JETTY_HOME/$JETTY_INSTALL_TRACE_FILE" ]
+      POSSIBLE_JETTY_HOME=("$L/"$N)
+      if [ ! -d "$POSSIBLE_JETTY_HOME" ]
       then
-        JETTY_HOME=
+        # Not a directory. skip.
+        unset POSSIBLE_JETTY_HOME
+      elif [ ! -f "$POSSIBLE_JETTY_HOME/$JETTY_INSTALL_TRACE_FILE" ]
+      then
+        # Trace file not found. skip.
+        unset POSSIBLE_JETTY_HOME
+      else
+        # Good hit, Use it
+        JETTY_HOME=$POSSIBLE_JETTY_HOME
+        # Break out of JETTY_DIR_NAMES loop
+        break
       fi
     done
-
-    [ "$JETTY_HOME" ] && break
+    if [ -n "$POSSIBLE_JETTY_HOME" ]
+    then
+      # We have found our JETTY_HOME
+      # Break out of STANDARD_LOCATIONS loop
+      break
+    fi
   done
 fi
 
@@ -229,7 +236,7 @@ fi
 # No JETTY_HOME yet? We're out of luck!
 ##################################################
 if [ -z "$JETTY_HOME" ]; then
-  echo "** ERROR: JETTY_HOME not set, you need to set it or install in a standard location" 
+  echo "** ERROR: JETTY_HOME not set, you need to set it or install in a standard location"
   exit 1
 fi
 
@@ -240,51 +247,19 @@ JETTY_HOME=$PWD
 #####################################################
 # Check that jetty is where we think it is
 #####################################################
-if [ ! -r "$JETTY_HOME/$JETTY_INSTALL_TRACE_FILE" ] 
+if [ ! -r "$JETTY_HOME/$JETTY_INSTALL_TRACE_FILE" ]
 then
   echo "** ERROR: Oops! Jetty doesn't appear to be installed in $JETTY_HOME"
   echo "** ERROR:  $JETTY_HOME/$JETTY_INSTALL_TRACE_FILE is not readable!"
   exit 1
 fi
 
-
-###########################################################
-# Get the list of config.xml files from the command line.
-###########################################################
-for ARG
-do
-  if [ -f "$ARG" ]
-  then
-    CONF="$ARG" 
-  elif [ -f "$JETTY_HOME/etc/$ARG" ]
-  then
-    CONF="$JETTY_HOME/etc/$ARG" 
-  elif [ -f "$ARG.xml" ] 
-  then
-    CONF="$ARG.xml" 
-  elif [ -f "$JETTY_HOME/etc/$ARG.xml" ] 
-  then
-    CONF="$JETTY_HOME/etc/$ARG.xml" 
-  else
-    echo "** ERROR: Cannot find configuration '$ARG' specified in the command line." 
-    exit 1
-  fi
-  if [ ! -r "$CONF" ] 
-  then
-    echo "** ERROR: Cannot read configuration '$ARG' specified in the command line." 
-    exit 1
-  fi
-
-  CONFIGS+=("$CONF")
-done
-
-
 ##################################################
 # Try to find this script's configuration file,
 # but only if no configurations were given on the
 # command line.
 ##################################################
-if [ -z "$JETTY_CONF" ] 
+if [ -z "$JETTY_CONF" ]
 then
   if [ -f /etc/jetty.conf ]
   then
@@ -298,51 +273,39 @@ fi
 ##################################################
 # Get the list of config.xml files from jetty.conf
 ##################################################
-if [ -z "$CONFIGS" ] && [ -f "$JETTY_CONF" ] && [ -r "$JETTY_CONF" ] 
+if [ -z "$CONFIGS" ] && [ -f "$JETTY_CONF" ] && [ -r "$JETTY_CONF" ]
 then
   while read -r CONF
   do
-    if [ ! -r "$CONF" ] 
-    then
-      echo "** WARNING: Cannot read '$CONF' specified in '$JETTY_CONF'" 
-    elif [ -f "$CONF" ] 
-    then
-      # assume it's a configure.xml file
-      CONFIGS+=("$CONF")
-    elif [ -d "$CONF" ] 
+    if expr "$CONF" : '#' >/dev/null ; then
+      continue
+    fi
+
+    if [ -d "$CONF" ]
     then
       # assume it's a directory with configure.xml files
       # for example: /etc/jetty.d/
       # sort the files before adding them to the list of CONFIGS
-      for file in "$CONF/"*.xml
+      for XMLFILE in "$CONF/"*.xml
       do
-        if [ -r "$FILE" ] && [ -f "$FILE" ] 
+        if [ -r "$XMLFILE" ] && [ -f "$XMLFILE" ]
         then
-          CONFIGS+=("$FILE")
+          CONFIGS+=("$XMLFILE")
         else
-          echo "** WARNING: Cannot read '$FILE' specified in '$JETTY_CONF'" 
+          echo "** WARNING: Cannot read '$XMLFILE' specified in '$JETTY_CONF'"
         fi
       done
     else
-      echo "** WARNING: Don''t know what to do with '$CONF' specified in '$JETTY_CONF'" 
+      # assume it's a command line parameter (let start.jar deal with its validity)
+      CONFIGS+=("$CONF")
     fi
   done < "$JETTY_CONF"
 fi
 
 #####################################################
-# Run the standard server if there's nothing else to run
-#####################################################
-if [ "${#CONFIGS[@]}" -eq 0 ] 
-then
-  #CONFIGS=("$JETTY_HOME/etc/jetty-logging.xml" "$JETTY_HOME/etc/jetty.xml")
-  CONFIGS=("$JETTY_HOME/etc/jetty.xml")
-fi
-
-
-#####################################################
 # Find a location for the pid file
 #####################################################
-if [ -z "$JETTY_RUN" ] 
+if [ -z "$JETTY_RUN" ]
 then
   JETTY_RUN=$(findDirectory -w /var/run /usr/var/run /tmp)
 fi
@@ -350,98 +313,29 @@ fi
 #####################################################
 # Find a PID for the pid file
 #####################################################
-if [ -z "$JETTY_PID" ] 
+if [ -z "$JETTY_PID" ]
 then
   JETTY_PID="$JETTY_RUN/jetty.pid"
 fi
 
-
 ##################################################
-# Check for JAVA_HOME
+# Setup JAVA if unset
 ##################################################
-if [ -z "$JAVA_HOME" ]
+if [ -z "$JAVA" ]
 then
-  # If a java runtime is not defined, search the following
-  # directories for a JVM and sort by version. Use the highest
-  # version number.
-
-  # Java search path
-  JAVA_LOCATIONS=(
-      "/usr/lib/jvm/java-6-openjdk"
-      "/usr/lib/jvm/java-6-sun"
-      "/usr/lib/jvm/java-1.5.0-sun"
-      "/usr/lib/jvm/java-gcj"
-      "/usr/lib/j2sdk1.6-sun"
-      "/usr/lib/j2sdk1.5-sun"
-      "/usr/lib/j2sdk1.4-sun"
-      "/usr/lib/j2sdk1.4"
-      "/usr/lib/j2se/1.4"
-      "/usr/lib/j2sdk1.3"
-      "/usr/lib/j2se/1.3"
-      "/usr/lib/kaffe"
-      )
-  IFS=: read JVERSION JAVA < <(
-    for N in java jdk jre
-    do
-      for L in "${JAVA_LOCATIONS[@]}"
-      do
-        [ -d "$L" ] || continue 
-        find "$L" -name "$N" ! -type d ! -path '*threads*' | while read JAVA; do
-          [ -x "$JAVA" ] || continue
-
-          JAVA_VERSION=$("$JAVA" -version 2>&1) || continue
-          IFS='"_' read _ JAVA_VERSION _ <<< "$JAVA_VERSION"
-
-          [ "$JAVA_VERSION" ] || continue
-          expr "$JAVA_VERSION" '<' '1.2' >/dev/null && continue
-
-          echo "$JAVA_VERSION:$JAVA"
-        done
-      done
-    done | sort)
-
-  # JAVA_HOME=${JAVA%/*}
-  # while [ "$JAVA_HOME" ] && [ ! -f "$JAVA_HOME/lib/tools.jar" ] ; do
-  #   JAVA_HOME=${JAVA_HOME%/*}
-  # done
-  # if [ -z "$JAVA_HOME" ]
-  # then
-  #   echo "** ERROR: Java installation at '$JAVA' doesn't appear to be valid or complete." 
-  #   exit 1
-  # fi
-
-  (( DEBUG )) && echo "Found java '$JAVA' at '$JAVA_HOME'"
-fi
-
-
-##################################################
-# Determine which JVM of version >1.2
-# Try to use JAVA_HOME
-##################################################
-if [ -z "$JAVA" ] && [ "$JAVA_HOME" ]
-then
-  if [ "$JAVACMD" ] 
-  then
-    JAVA="$JAVACMD" 
-  else
-    [ -x "$JAVA_HOME/bin/jre" -a ! -d "$JAVA_HOME/bin/jre" ] && JAVA=$JAVA_HOME/bin/jre
-    [ -x "$JAVA_HOME/bin/java" -a ! -d "$JAVA_HOME/bin/java" ] && JAVA=$JAVA_HOME/bin/java
-  fi
+  JAVA=$(which java)
 fi
 
 if [ -z "$JAVA" ]
 then
-  echo "Cannot find a JRE or JDK. Please set JAVA_HOME to a >=1.2 JRE" 2>&2
+  echo "Cannot find a Java JDK. Please set either set JAVA or put java (>=1.5) in your PATH." 2>&2
   exit 1
 fi
-
-JAVA_VERSION=$("$JAVA" -version 2>&1) || continue
-IFS='"_' read _ JAVA_VERSION _ <<< "$JAVA_VERSION"
 
 #####################################################
 # See if JETTY_PORT is defined
 #####################################################
-if [ "$JETTY_PORT" ] 
+if [ "$JETTY_PORT" ]
 then
   JAVA_OPTIONS+=("-Djetty.port=$JETTY_PORT")
 fi
@@ -477,12 +371,14 @@ JAVA_OPTIONS+=("-Djetty.home=$JETTY_HOME" "-Djava.io.tmpdir=$TMPDIR")
 JETTY_START=$JETTY_HOME/start.jar
 [ ! -f "$JETTY_START" ] && JETTY_START=$JETTY_HOME/lib/start.jar
 
-#RUN_ARGS=("${JAVA_OPTIONS[@]}" -jar "$JETTY_START" --fromDaemon $JETTY_ARGS "${CONFIGS[@]}")
-RUN_ARGS=("${JAVA_OPTIONS[@]}" -jar "$JETTY_START" $JETTY_ARGS "${CONFIGS[@]}")
-RUN_CMD=("$JAVA" "${RUN_ARGS[@]}")
+START_INI=$(dirname $JETTY_START)/start.ini
+[ -r "$START_INI" ] || START_INI=""
+
+RUN_ARGS=(${JAVA_OPTIONS[@]} -jar "$JETTY_START" $JETTY_ARGS "${CONFIGS[@]}")
+RUN_CMD=("$JAVA" ${RUN_ARGS[@]})
 
 #####################################################
-# Comment these out after you're happy with what 
+# Comment these out after you're happy with what
 # the script is doing.
 #####################################################
 if (( DEBUG ))
@@ -495,7 +391,6 @@ then
   echo "CONFIGS        =  ${CONFIGS[*]}"
   echo "JAVA_OPTIONS   =  ${JAVA_OPTIONS[*]}"
   echo "JAVA           =  $JAVA"
-  echo "RUN_ARGS       =  ${RUN_ARGS[*]}"
   echo "RUN_CMD        =  ${RUN_CMD}"
 fi
 
@@ -506,16 +401,19 @@ case "$ACTION" in
   start)
     echo -n "Starting Jetty: "
 
-    if (( NO_START )); then 
+    if (( NO_START )); then
       echo "Not starting jetty - NO_START=1";
       exit
     fi
 
-    if type start-stop-daemon > /dev/null 2>&1 
+    if type start-stop-daemon > /dev/null 2>&1
     then
-      [ -z "$JETTY_USER" ] && JETTY_USER=$USER
-      (( UID == 0 )) && CH_USER=-c$JETTY_USER
-      if USER=$JETTY_USER start-stop-daemon -S -p"$JETTY_PID" "$CH_USER" -d"$JETTY_HOME" -b -m -a "$JAVA" -- "${RUN_ARGS[@]}"
+      unset CH_USER
+      if [ -n "$JETTY_USER" ]
+      then
+        CH_USER="-c$JETTY_USER"
+      fi
+      if start-stop-daemon -S -p"$JETTY_PID" $CH_USER -d"$JETTY_HOME" -b -m -a "$JAVA" -- "${RUN_ARGS[@]}" --daemon
       then
         sleep 1
         if running "$JETTY_PID"
@@ -540,13 +438,13 @@ case "$ACTION" in
         fi
       fi
 
-      if [ "$JETTY_USER" ] 
+      if [ "$JETTY_USER" ]
       then
         touch "$JETTY_PID"
         chown "$JETTY_USER" "$JETTY_PID"
         # FIXME: Broken solution: wordsplitting, pathname expansion, arbitrary command execution, etc.
-        su - "$JETTY_USER" -c "
-          ${RUN_CMD[*]} &
+        sudo -u "$JETTY_USER" -- bash -c "
+          exec ${RUN_CMD[*]} --daemon &
           disown \$!
           echo \$! > '$JETTY_PID'"
       else
@@ -554,8 +452,8 @@ case "$ACTION" in
         disown $!
         echo $! > "$JETTY_PID"
       fi
-	
-      echo "STARTED Jetty `date` with ${RUN_CMD[*]}" 
+
+      echo "STARTED Jetty `date`"
     fi
 
     ;;
@@ -564,7 +462,7 @@ case "$ACTION" in
     echo -n "Stopping Jetty: "
     if type start-stop-daemon > /dev/null 2>&1; then
       start-stop-daemon -K -p"$JETTY_PID" -d"$JETTY_HOME" -a "$JAVA" -s HUP
-      
+
       TIMEOUT=30
       while running "$JETTY_PID"; do
         if (( TIMEOUT-- == 0 )); then
@@ -579,7 +477,7 @@ case "$ACTION" in
     else
       PID=$(cat "$JETTY_PID" 2>/dev/null)
       kill "$PID" 2>/dev/null
-      
+
       TIMEOUT=30
       while running $JETTY_PID; do
         if (( TIMEOUT-- == 0 )); then
@@ -646,16 +544,17 @@ case "$ACTION" in
     echo "JETTY_PID      =  $JETTY_PID"
     echo "JETTY_PORT     =  $JETTY_PORT"
     echo "JETTY_LOGS     =  $JETTY_LOGS"
+    echo "START_INI      =  $START_INI"
     echo "CONFIGS        =  ${CONFIGS[*]}"
     echo "JAVA_OPTIONS   =  ${JAVA_OPTIONS[*]}"
     echo "JAVA           =  $JAVA"
     echo "CLASSPATH      =  $CLASSPATH"
     echo "RUN_CMD        =  ${RUN_CMD[*]}"
     echo
-    
-    if [ -f "$JETTY_RUN/jetty.pid" ]
+
+    if [ -f "$JETTY_PID" ]
     then
-      echo "Jetty running pid=$(< "$JETTY_RUN/jetty.pid")"
+      echo "Jetty running pid=$(< "$JETTY_PID")"
       exit 0
     fi
     exit 1
